# Generated by Django 5.1.5 on 2025-01-16 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "baseuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("phone_number", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")], max_length=5
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("users.baseuser",),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "baseuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("tax_number", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("users.baseuser",),
        ),
    ]
