# Generated by Django 5.1.5 on 2025-01-17 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customer_supplier"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
