# Generated by Django 5.1.5 on 2025-01-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0002_privatives"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Privatives",
            new_name="Privative",
        ),
    ]
