# Generated by Django 5.1.5 on 2025-01-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0007_privative_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Privative",
        ),
    ]
