# Generated by Django 5.1.5 on 2025-01-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0003_rename_privatives_privative"),
    ]

    operations = [
        migrations.AddField(
            model_name="privative",
            name="area",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="privative",
            name="building",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="privatives",
                to="buildings.building",
            ),
            preserve_default=False,
        ),
    ]
