# Generated by Django 5.1.5 on 2025-01-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0005_alter_privative_building"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privative",
            name="building",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="privatives",
                to="buildings.building",
            ),
            preserve_default=False,
        ),
    ]
